include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:
    - avoid_unclosed_stream_controller
    - avoid_uncancelled_stream_subscription
    - avoid_undisposed_controller
